CREATE TABLE AWARDS(
    AWARD_ID VARCHAR2(35),
    A_DESCRIPTION VARCHAR2(35), 
    POINTS_REQUIRED NUMBER(20,0), 
    PRIMARY KEY(AWARD_ID)
);

CREATE TABLE PASSENGERS( 
    PASS_ID VARCHAR2(35),
    PNAME VARCHAR2(35), 
    SSN NUMBER(20,0), 
    GENDER VARCHAR2(35), 
    EMAIL VARCHAR2(35), 
    OCCUPATION VARCHAR2(35), 
    DOB DATE, 
    IS_MEMBER VARCHAR2(35), 
    PRIMARY KEY(PASS_ID)
);

CREATE TABLE PHONE(
    PASS_ID VARCHAR2(35),
    PHONE_NUMBER NUMBER(15,0), 
    PRIMARY KEY(PASS_ID,PHONE_NUMBER), 
    FOREIGN KEY(PASS_ID) 
    REFERENCES PASSENGERS
);

CREATE TABLE ADDRESS(
    PASS_ID VARCHAR2(35), 
    HOME_NUM NUMBER(11,0), 
    ZIP VARCHAR2(20),
    STREET VARCHAR2(35), 
    CITY VARCHAR2(35), 
    STATE VARCHAR2(35), 
    PRIMARY KEY(PASS_ID,HOME_NUM,ZIP,STREET,CITY,STATE),
    FOREIGN KEY(PASS_ID) 
    REFERENCES PASSENGERS
);

CREATE TABLE EXCHGCENTERS(
    CENTER_ID VARCHAR2(35), 
    CENTER_NAME VARCHAR2(35), 
    C_LOCATION VARCHAR2(35),
    PRIMARY KEY(CENTER_ID)
);

CREATE TABLE POINT_ACCOUNTS(
    POINT_ACCOUNT_ID VARCHAR2(35), 
    PASS_ID VARCHAR2(35) NOT NULL, 
    TOTAL_POINTS VARCHAR2(35), 
    PRIMARY KEY(POINT_ACCOUNT_ID), 
    FOREIGN KEY(PASS_ID) 
    REFERENCES PASSENGERS
);

CREATE TABLE LOGIN(
    USERNAME VARCHAR2(35), 
    PASS_ID VARCHAR2(35) NOT NULL, 
    PASSWORD VARCHAR2(35), 
    PRIMARY KEY(USERNAME), 
    FOREIGN KEY(PASS_ID) 
    REFERENCES PASSENGERS
);

CREATE TABLE PASSENGERS_AWARDS(
    AWARD_ID VARCHAR2(35), 
    PASS_ID VARCHAR2(35), 
    CENTER_ID VARCHAR2(35) NOT NULL,
    POINT_ACCOUNT_ID VARCHAR2(35) NOT NULL,
    REDEMPTION_DATE DATE,
    QUANTITY  NUMBER(5,0),
    PRIMARY KEY(AWARD_ID,PASS_ID,CENTER_ID,POINT_ACCOUNT_ID),
    FOREIGN KEY(CENTER_ID) 
    REFERENCES EXCHGCENTERS, 
    FOREIGN KEY(POINT_ACCOUNT_ID) 
    REFERENCES POINT_ACCOUNTS, 
    FOREIGN KEY(AWARD_ID) 
    REFERENCES AWARDS, 
    FOREIGN KEY(PASS_ID) 
    REFERENCES PASSENGERS
);

CREATE TABLE CARDS(
    CARD_ID VARCHAR2(35), 
    EXPIRY_DATE DATE, 
    IS_VALID VARCHAR2(35), 
    PASS_ID VARCHAR2(35) NOT NULL,
    C_DATE DATE, 
    PRIMARY KEY(CARD_ID), 
    FOREIGN KEY(PASS_ID) 
    REFERENCES PASSENGERS
);

CREATE TABLE EMPL_INCENTIVES(
    PASSENGER_ID VARCHAR2(35), 
    INCENTIVE_ID VARCHAR2(35),
    PERCENT_INCREASE VARCHAR2(35),
    PRIMARY KEY(INCENTIVE_ID)
);

CREATE TABLE EMPL_REFERRALS(
    REFERRAL_ID VARCHAR2(35), 
    PASSENGER_ID VARCHAR(35),
    PERCENT_INCREASE VARCHAR2(35), 
    PRIMARY KEY(REFERRAL_ID)
);

CREATE TABLE PROMOTIONS(
    PROMO_ID VARCHAR2(35), 
    PROMO_ACTION VARCHAR2(35), 
    PROMO_PERIOD VARCHAR2(35), 
    P_DESCRIPTION VARCHAR2(35), 
    PRIMARY KEY (PROMO_ID)
);

CREATE TABLE TRIPS(
    TRIP_ID VARCHAR(35), 
    TRIP_MILES VARCHAR2(35),
    SOURCE VARCHAR2(35),
    DESTINATION VARCHAR2(35), 
    DEPT_DATETIME VARCHAR2(35), 
    ARRIVAL_DATETIME VARCHAR2(35),
    PRIMARY KEY(TRIP_ID)
);

CREATE TABLE FLIGHTS(
    FLIGHT_ID VARCHAR2(35), 
    FLIGHT_MILES NUMBER(10,0), 
    SOURCE VARCHAR2(35), 
    DESTINATION VARCHAR2(35), 
    ARRIVAL_DATETIME VARCHAR2(35), 
    DEPT_DATETIME VARCHAR2(35), 
    INCENTIVE_ID VARCHAR2(35), 
    REFERRAL_ID VARCHAR2(35), 
    PASS_ID VARCHAR2(35) NOT NULL, 
    POINT_ACCOUNT_ID VARCHAR2(35) NOT NULL, 
    PRIMARY KEY(FLIGHT_ID), 
    FOREIGN KEY(POINT_ACCOUNT_ID) 
    REFERENCES POINT_ACCOUNTS, 
    FOREIGN KEY(PASS_ID) 
    REFERENCES PASSENGERS,
    FOREIGN KEY(INCENTIVE_ID) 
    REFERENCES EMPL_INCENTIVES, 
    FOREIGN KEY(REFERRAL_ID) 
    REFERENCES EMPL_REFERRALS
);

CREATE TABLE FLIGHTS_TRIPS(
    TRIP_ID VARCHAR2(35),
    FLIGHT_ID VARCHAR2(35) NOT NULL,
    PRIMARY KEY(TRIP_ID, FLIGHT_ID), 
    FOREIGN KEY(TRIP_ID) 
    REFERENCES TRIPS, 
    FOREIGN KEY(FLIGHT_ID) 
    REFERENCES FLIGHTS
); 

CREATE TABLE PROMOTIONS_FLIGHTS(
    FLIGHT_ID VARCHAR(35), 
    PROMO_ID VARCHAR2(35), 
    PRIMARY KEY(FLIGHT_ID,PROMO_ID), 
    FOREIGN KEY(PROMO_ID) 
    REFERENCES PROMOTIONS,
    FOREIGN KEY(FLIGHT_ID) 
    REFERENCES FLIGHTS
);
